version: "3.8"

services:
  charm-shop:
    build: .
    ports:
      - 8081:8080
    environment:
      - PG_DB_URL=jdbc:postgresql://postgres:5432/postgres
      - PG_DB_USERNAME=postgres
      - PG_DB_PASSWORD=pass
    container_name: charm_shop_container
    depends_on:
      - postgres
    volumes:
      - ./logs/application.log:/logs/application.log
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
    container_name: postgres_container
    volumes:
     - db-data:/var/lib/postgresql/data
  promtail:
    image: grafana/promtail:latest
    container_name: promtail_container
    volumes:
      - ./promtail/promtail-docker-config.yml:/etc/promtail/docker-config.yaml
      - ./logs/application.log:/var/log/application.log
    command: "--config.file=/etc/promtail/docker-config.yaml"
  loki:
    image: grafana/loki:latest
    container_name: loki_container
    ports:
      - 3100:3100
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - loki
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  db-data:
    driver: local
