spring:
  datasource:
    url: ${PG_DB_URL}
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate